# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9b04a1739e8b6c1d77df7c68a4fc984630d0abe9a0b179548a509fc826eb83afe237cfb3fbb5b033e81411189eba2896c591e83b2fb3a36c56b837c478c24a1

test:
  secret_key_base: 93f888b2d481c683a0772359f03cca8ba5585a8e58f3ad496a991aab6f8c0f93a6387ba35e79d0af8e8756b26d0e9b580ecda940291dc754ff6b7fdb68115581

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
